sudo: false

os:
  - linux

dist:
  - xenial

language: python

python:
  - "3.6"
  - "3.7"

cache: pip

services:
  - xvfb

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --add channels conda-forge
  - conda config --set always_yes yes --set changeps1 no  

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment  
  - conda install --yes --file requirements/conda_requirements.txt
  - pip install -r requirements/test_requirements.txt
  - pip install Cython --install-option="--no-cython-compile"
  - pip install pkgconfig
  - python setup.py install

script: pytest --pep8 --cov=./

notifications:
  email: false

# after_success:
#   - codecov
