name: Verify pip-installability

on: [push]

jobs:
  deploy:
    name: Verify pip-installability
    runs-on: ${{ matrix.operating-system }}

    strategy:
      max-parallel: 4
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Test
      run:
        echo $GITHUB_REF

    - name: Install only using pip
      run:
        git+https://github.com/PMEAL/porespy.git@dev

    - name: Test the installation
      run:
        python -c "import porespy"
